# Generated by Django 4.2.4 on 2023-10-16 13:52

from django.db import migrations, models
import django.db.models.deletion
import hotelpro.apps.room.room_enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField(unique=True, verbose_name='room_number')),
                ('status', models.CharField(choices=[('available', 'v'), ('full', 'u'), ('reserved', 'e')], default=hotelpro.apps.room.room_enums.STATUS['available'], max_length=32, verbose_name='status')),
                ('price_per_day', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='price for one days')),
                ('room_type', models.CharField(choices=[('Standard Room', 't'), ('Deluxe Room', 'e'), ('Suite', 'u'), ('Accessible Room', 'c'), ('Pet-Friendly Room', 'e'), ('Connecting Rooms', 'o'), ('Executive Room', 'x')], default=hotelpro.apps.room.room_enums.RoomType['standard_room'], max_length=100, verbose_name='room type')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='room detail')),
                ('num_beds', models.PositiveIntegerField(verbose_name='count of the room beds')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='product visibility')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='date sub-product created')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', help_text='format: required, default-default.png', upload_to='images/', verbose_name='room image')),
                ('alt_text', models.CharField(help_text='format: required, max-255', max_length=255, verbose_name='alternative text')),
                ('is_default', models.BooleanField(help_text='format:default=false true=default image', verbose_name='room default image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='product visibility')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='date sub-product created')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_room', to='room.room')),
            ],
            options={
                'verbose_name': 'room image',
                'verbose_name_plural': 'room images',
            },
        ),
    ]
