# Generated by Django 4.2.4 on 2023-09-18 12:49

import datetime
from django.db import migrations, models
import hotelpro.apps.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='email',
        ),
        migrations.AddField(
            model_name='customuser',
            name='verify',
            field=models.BooleanField(default=False, verbose_name='verify'),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_time_end',
            field=models.DateTimeField(default=hotelpro.apps.account.models.default_expire_time, null=True, verbose_name='end of expire time'),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_time_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='start of expire time'),
        ),
    ]
