# Generated by Django 4.2.4 on 2023-09-05 11:09

import django.core.validators
from django.db import migrations, models
import hotelpro.apps.account.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]
 
    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', hotelpro.apps.account.manager.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+989xxxxxxxxx'. Up to 14 digits allowed.", regex='^\\+{1}989\\d{9}$')], verbose_name='Phone number'),
        ),
    ]
