# Generated by Django 4.2.4 on 2023-09-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userotp_expire_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='code_type',
            field=models.IntegerField(choices=[(1, 'sing up'), (2, 'LOGIN'), (3, 'email')], default=1, null=True, verbose_name='code type'),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_time_start',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='start of expire time'),
        ),
    ]
